version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'gh-pages' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
